name: Setup Python env

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install the project
      run: uv sync --locked --all-extras --dev
      shell: bash
