name: Setup Python env

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: poetry-0  # increment to reset cache

    - name: Add poetry to PATH
      shell: bash
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Python poetry
      uses: snok/install-poetry@v1
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Configure poetry
      if: steps.cached-poetry.outputs.cache-hit == 'true'
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install --no-interaction --no-root

    - name: Install project
      shell: bash
      run: poetry install --no-interaction
